#Dagger damage multiplier when hitting targets not targeting user
#Range: 1.0 ~ 1000.0
dagger_bonus = 2.0
#Claw damage bonus for each consecutive hit
#Range: 0.0 ~ 10.0
claw_bonus = 0.1
#Claw damage bonus maximum hit for one claw (two claw has double maximum)
#Range: 1 ~ 1000
claw_max = 5
#Claw damage bonus timeout
#Range: 1 ~ 1000
claw_timeout = 60
#Claw block damage time
#Range: 0 ~ 1000
claw_block_time = 3
#Shield reflect cost
#Range: 0.0 ~ 1.0
reflectCost = 0.2
#Shadow Hunter teleport distance
#Range: 1 ~ 128
shadowHunterDistance = 8
#Haunting Demon of the End teleport distance
#Range: 1 ~ 128
hauntingDemonDistance = 64
#Hammer of Incarceration effect radius
#Range: 1 ~ 64
hammerOfIncarcerationRadius = 8
#Hammer of Incarceration effect duration
#Range: 1 ~ 60000
hammerOfIncarcerationDuration = 60
#Dogmatic Standoff absorption gain percentage
#Range: 1.0E-4 ~ 1.0
dogmaticStandoffGain = 0.02
#Dogmatic Standoff absorption max percentage
#Range: 1.0E-4 ~ 100.0
dogmaticStandoffMax = 0.1

